version: "3.9"

services:

  api_gateway:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    networks:
      - adamhutchison:postcodes
    ports:
      - 8000:8000

  auth_server:
    build:
      context: ./auth-server
      dockerfile: ./Dockerfile
    networks:
      - adamhutchison:postcodes
    depends_on:
      - auth_database

  auth_database:
    build:
      context: ./auth-database
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - adamhutchison:postcodes
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"

  postcode_service:
    build:
      context: ./postcode-search
      dockerfile: ./Dockerfile
    networks:
      - adamhutchison:postcodes
      
networks:
  adamhutchison:postcodes:
    name: adamhutchison:postcodes